// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: accounts.sql

package db

import (
	"context"

	"github.com/shopspring/decimal"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    name,
    currency_id,
    balance    
) VALUES (
  $1, $2, $3
)
RETURNING id, name, currency_id, balance, created_at, updated_at
`

type CreateAccountParams struct {
	Name       string
	CurrencyID int16
	Balance    decimal.Decimal
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.Name, arg.CurrencyID, arg.Balance)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CurrencyID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts
 WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAccount, id)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, name, currency_id, balance, created_at, updated_at
  FROM accounts
 WHERE id = $1
 LIMIT 1
`

func (q *Queries) GetAccount(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CurrencyID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAccountBalance = `-- name: UpdateAccountBalance :one
UPDATE accounts
   SET balance = balance + $2,
       updated_at = NOW()
 WHERE id = $1
RETURNING id, name, currency_id, balance, created_at, updated_at
`

type UpdateAccountBalanceParams struct {
	ID     int64
	Amount decimal.Decimal
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountBalance, arg.ID, arg.Amount)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CurrencyID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
