// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package db

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    user_id,
    name,
    currency_id,
    balance
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, name, currency_id, balance, created_at, updated_at, user_id
`

type CreateAccountParams struct {
	UserID     int64  `json:"userId"`
	Name       string `json:"name"`
	CurrencyID int16  `json:"currencyId"`
	Balance    int64  `json:"balance"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.UserID,
		arg.Name,
		arg.CurrencyID,
		arg.Balance,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CurrencyID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts
 WHERE id = $1
   AND user_id = $2
`

type DeleteAccountParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"userId"`
}

func (q *Queries) DeleteAccount(ctx context.Context, arg DeleteAccountParams) error {
	_, err := q.db.Exec(ctx, deleteAccount, arg.ID, arg.UserID)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, name, currency_id, balance, created_at, updated_at, user_id
  FROM accounts
 WHERE id = $1
   AND user_id = $2
 LIMIT 1
`

type GetAccountParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"userId"`
}

func (q *Queries) GetAccount(ctx context.Context, arg GetAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, arg.ID, arg.UserID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CurrencyID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, name, currency_id, balance, created_at, updated_at, user_id
  FROM accounts
 WHERE user_id = $1
 ORDER BY id
 LIMIT $2
OFFSET $3
`

type ListAccountsParams struct {
	UserID int64 `json:"userId"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CurrencyID,
			&i.Balance,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountBalance = `-- name: UpdateAccountBalance :one
UPDATE accounts
   SET balance = balance + $2,
       updated_at = NOW()
 WHERE id = $1
RETURNING id, name, currency_id, balance, created_at, updated_at, user_id
`

type UpdateAccountBalanceParams struct {
	ID     int64 `json:"id"`
	Amount int64 `json:"amount"`
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountBalance, arg.ID, arg.Amount)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CurrencyID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
