// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (
    user_id,
    name,
    transaction_type_id
) VALUES (
  $1, $2, $3
)
RETURNING id, name, transaction_type_id, created_at, updated_at, user_id
`

type CreateCategoryParams struct {
	UserID            int64  `json:"userId"`
	Name              string `json:"name"`
	TransactionTypeID int16  `json:"transactionTypeId"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.UserID, arg.Name, arg.TransactionTypeID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TransactionTypeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories
 WHERE id = $1
   AND user_id = $2
`

type DeleteCategoryParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"userId"`
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteCategory, arg.ID, arg.UserID)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, transaction_type_id, created_at, updated_at, user_id
  FROM categories
 WHERE id = $1
   AND user_id = $2
 LIMIT 1
`

type GetCategoryParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"userId"`
}

func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, arg.ID, arg.UserID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TransactionTypeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, transaction_type_id, created_at, updated_at, user_id
  FROM categories
 WHERE user_id = $1
 ORDER BY id
 LIMIT $2
OFFSET $3
`

type ListCategoriesParams struct {
	UserID int64 `json:"userId"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TransactionTypeID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
   SET name = COALESCE($2, name),
       transaction_type_id = COALESCE($3, transaction_type_id),
       updated_at = NOW()
 WHERE id = $1
   AND user_id = $4
RETURNING id, name, transaction_type_id, created_at, updated_at, user_id
`

type UpdateCategoryParams struct {
	ID                int64       `json:"id"`
	Name              pgtype.Text `json:"name"`
	TransactionTypeID pgtype.Int2 `json:"transactionTypeId"`
	UserID            int64       `json:"userId"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.TransactionTypeID,
		arg.UserID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TransactionTypeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
