// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: categories.sql

package db

import (
	"context"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (
    name, 
    transaction_type_id
) VALUES (
  $1, $2
)
RETURNING id, name, transaction_type_id, created_at, updated_at
`

type CreateCategoryParams struct {
	Name              string
	TransactionTypeID int32
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name, arg.TransactionTypeID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TransactionTypeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories
 WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, transaction_type_id, created_at, updated_at
  FROM categories
 WHERE id = $1
 LIMIT 1
`

func (q *Queries) GetCategory(ctx context.Context, id int32) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TransactionTypeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :exec
UPDATE categories
   SET name = $2,
       transaction_type_id = $3
 WHERE id = $1
`

type UpdateCategoryParams struct {
	ID                int32
	Name              string
	TransactionTypeID int32
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error {
	_, err := q.db.Exec(ctx, updateCategory, arg.ID, arg.Name, arg.TransactionTypeID)
	return err
}
