// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: currencies.sql

package moneytor

import (
	"context"
)

const getCurrency = `-- name: GetCurrency :one
SELECT id, currency_code 
  FROM currencies
 WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCurrency(ctx context.Context, id int16) (Currency, error) {
	row := q.db.QueryRow(ctx, getCurrency, id)
	var i Currency
	err := row.Scan(&i.ID, &i.CurrencyCode)
	return i, err
}
