// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: currencies.sql

package db

import (
	"context"
)

const getCurrency = `-- name: GetCurrency :one
SELECT id, code 
  FROM currencies
 WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCurrency(ctx context.Context, id int16) (Currency, error) {
	row := q.db.QueryRow(ctx, getCurrency, id)
	var i Currency
	err := row.Scan(&i.ID, &i.Code)
	return i, err
}

const listCurrencies = `-- name: ListCurrencies :many
SELECT id, code 
  FROM currencies
 ORDER BY id
`

func (q *Queries) ListCurrencies(ctx context.Context) ([]Currency, error) {
	rows, err := q.db.Query(ctx, listCurrencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Currency
	for rows.Next() {
		var i Currency
		if err := rows.Scan(&i.ID, &i.Code); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
