// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (
     name
    ,note
    ,from_account_id  
    ,to_account_id  
    ,category_id 
    ,amount      
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, name, note, from_account_id, to_account_id, category_id, amount, created_at
`

type CreateEntryParams struct {
	Name          string
	Note          string
	FromAccountID int64
	ToAccountID   pgtype.Int8
	CategoryID    int64
	Amount        decimal.Decimal
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRow(ctx, createEntry,
		arg.Name,
		arg.Note,
		arg.FromAccountID,
		arg.ToAccountID,
		arg.CategoryID,
		arg.Amount,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Note,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.CategoryID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const getEntry = `-- name: GetEntry :one
SELECT id, name, note, from_account_id, to_account_id, category_id, amount, created_at
  FROM entries
 WHERE id = $1
 LIMIT 1
`

func (q *Queries) GetEntry(ctx context.Context, id int64) (Entry, error) {
	row := q.db.QueryRow(ctx, getEntry, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Note,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.CategoryID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const listEntries = `-- name: ListEntries :many
SELECT id, name, note, from_account_id, to_account_id, category_id, amount, created_at
  FROM entries
 ORDER BY id DESC
 LIMIT $1
 OFFSET $2
`

type ListEntriesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error) {
	rows, err := q.db.Query(ctx, listEntries, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Note,
			&i.FromAccountID,
			&i.ToAccountID,
			&i.CategoryID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesByAccountID = `-- name: ListEntriesByAccountID :many
SELECT id, name, note, from_account_id, to_account_id, category_id, amount, created_at
  FROM entries
 WHERE from_account_id = $3 OR to_account_id = $3
 ORDER BY id DESC
 LIMIT $1
 OFFSET $2
`

type ListEntriesByAccountIDParams struct {
	Limit     int32
	Offset    int32
	AccountID int64
}

func (q *Queries) ListEntriesByAccountID(ctx context.Context, arg ListEntriesByAccountIDParams) ([]Entry, error) {
	rows, err := q.db.Query(ctx, listEntriesByAccountID, arg.Limit, arg.Offset, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Note,
			&i.FromAccountID,
			&i.ToAccountID,
			&i.CategoryID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
