// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entries.sql

package db

import (
	"context"

	"github.com/shopspring/decimal"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (
     name
    ,note
    ,account_id  
    ,category_id 
    ,amount      
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, name, note, account_id, category_id, amount, created_at
`

type CreateEntryParams struct {
	Name       string
	Note       string
	AccountID  int64
	CategoryID int32
	Amount     decimal.Decimal
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRow(ctx, createEntry,
		arg.Name,
		arg.Note,
		arg.AccountID,
		arg.CategoryID,
		arg.Amount,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Note,
		&i.AccountID,
		&i.CategoryID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const listEntries = `-- name: ListEntries :many
SELECT id, name, note, account_id, category_id, amount, created_at
  FROM entries
 ORDER BY id DESC
 LIMIT $1
 OFFSET $2
`

type ListEntriesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error) {
	rows, err := q.db.Query(ctx, listEntries, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Note,
			&i.AccountID,
			&i.CategoryID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesByAccountID = `-- name: ListEntriesByAccountID :many
SELECT id, name, note, account_id, category_id, amount, created_at
  FROM entries
 WHERE account_id = $1
 ORDER BY id DESC
 LIMIT $2
 OFFSET $3
`

type ListEntriesByAccountIDParams struct {
	AccountID int64
	Limit     int32
	Offset    int32
}

func (q *Queries) ListEntriesByAccountID(ctx context.Context, arg ListEntriesByAccountIDParams) ([]Entry, error) {
	rows, err := q.db.Query(ctx, listEntriesByAccountID, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Note,
			&i.AccountID,
			&i.CategoryID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
