// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	DeleteAccount(ctx context.Context, id int64) error
	DeleteCategory(ctx context.Context, id int32) error
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetCategory(ctx context.Context, id int32) (Category, error)
	GetCurrency(ctx context.Context, id int16) (Currency, error)
	GetTransactionType(ctx context.Context, id int16) (TransactionType, error)
	ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error)
	ListCurrencies(ctx context.Context) ([]Currency, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error)
	ListTransactionTypes(ctx context.Context) ([]TransactionType, error)
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
}

var _ Querier = (*Queries)(nil)
