// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transaction_type.sql

package db

import (
	"context"
)

const getTransactionType = `-- name: GetTransactionType :one
SELECT id, name 
  FROM transaction_types
 WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTransactionType(ctx context.Context, id int16) (TransactionType, error) {
	row := q.db.QueryRow(ctx, getTransactionType, id)
	var i TransactionType
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listTransactionTypes = `-- name: ListTransactionTypes :many
SELECT id, name 
  FROM transaction_types
 ORDER BY id
`

func (q *Queries) ListTransactionTypes(ctx context.Context) ([]TransactionType, error) {
	rows, err := q.db.Query(ctx, listTransactionTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransactionType
	for rows.Next() {
		var i TransactionType
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
